version: '3'
services:
  cache_server:
    build:
      context: ./cache_server/
    container_name: varnish
    depends_on:
      - web_server
    volumes:
      - ./cache_server/default.vcl:/etc/varnish/default.vcl
      - ./cache_server/varnish:/etc/default/varnish
      - ./cache_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "80:80"
      - "6082:6082"
    links:
      - web_server
  redis:
    image: "redis:latest"
    container_name: redis_host
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"

  web_server:
    # image:->build:に変更してDockerfileの場所を指定
    build: ./html/
    container_name: apache2
    volumes:
      - ./html/php.ini:/usr/local/etc/php/php.ini
      - ./html/magento:/var/www/html
    ports:
      - 8080:8080
    depends_on:
      - "db"

  # MySQL
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  # phpMyAdmin
  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql_host
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8085:80
    depends_on:
      - "db"